config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :students, controllers: {
        registrations: 'students/registrations',
        sessions: 'students/sessions'
      }

  devise_for :instructors, controllers: {
        registrations: 'instructors/registrations',
        sessions: 'instructors/sessions'
      }

  resources :instructors do
    collection do
      get :tomorrow
    end
  end

  resources :students

  resources :schedules, only: [:new, :create, :destroy, :index, :show] do
    collection do
      get :courses
    end
    resources :reservations do
      collection do
        get :personal
        get :group
      end
    end
    resources :meetings, only: [:new, :create]
  end

  resources :reservations

  resources :meetings do
    resources :reviews, only: [:new, :create, :index]
    resources :messages
  end

  resources :contacts, only: [:new, :create, :index]


  root "users#sign_up"
  get "/users/sign_in"
  get "/users/sign_up"
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :icon
  has_many :schedules, dependent: :destroy

  validates :name, presence: true, length: {maximum: 20}, on: :update
  validates :age, presence: true, on: :update
  validates :profile, presence: true, length: {maximum: 300}, on: :update
  validates :status, presence: true, on: :update
  validates :industry, presence: true, on: :update
  validates :occupation, presence: true, on: :update

  scope :active, -> {where.not(name: nil)}

  def meetings
    self.schedules.select{|s| s.meeting }.map{|s| s.meeting}
  end

  def not_reviewed?
    meetings = self.meetings.select{|m| m.schedule.previous? }
    return meetings.select{|m| m.reviews.find{|r| r.instructor_id == self.id } }.count != meetings.count
  end

end

app/controllers/instructors/confirmations_controller.rb
# frozen_string_literal: true

class Instructors::ConfirmationsController < Devise::ConfirmationsController
  #GET /resource/confirmation/new
  def new
    super
  end

  #POST /resource/confirmation
  def create
    super
  end

  #GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  #The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  #The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/instructors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Instructors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/instructors/passwords_controller.rb
# frozen_string_literal: true

class Instructors::PasswordsController < Devise::PasswordsController
  #GET /resource/password/new
  def new
    super
  end

  #POST /resource/password
  def create
    super
  end

  #GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  #PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  #The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/instructors/registrations_controller.rb
# frozen_string_literal: true

class Instructors::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
  def new
    super
  end

  #POST /resource
  def create
    super
  end

  #GET /resource/edit
  def edit
    super
  end

  #PUT /resource
  def update
    super
  end

  #DELETE /resource
  def destroy
    super
  end

  #GET /resource/cancel
  #Forces the session data which is usually expired after sign
  #in to be expired now. This is useful if the user wants to
  #cancel oauth signing in/up in the middle of the process,
  #removing all OAuth session data.
  def cancel
    super
  end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  #If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
      keys: [:name, :profile, :age, :icon, :company, :status, :is_public, :industry, :occupation])
  end

  #The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  def after_update_path_for(resource)
    instructor_path(current_instructor)
  end

  #The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/instructors/sessions_controller.rb
# frozen_string_literal: true

class Instructors::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  #GET /resource/sign_in
  def new
    super
  end

  #POST /resource/sign_in
  def create
    super
  end

  #DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/instructors/unlocks_controller.rb
# frozen_string_literal: true

class Instructors::UnlocksController < Devise::UnlocksController
  #GET /resource/unlock/new
  def new
    super
  end

  #POST /resource/unlock
  def create
    super
  end

  #GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  protected

  #The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  #The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < UsersController

  def index
    today_instructor_ids = Schedule.today.map{|s| s.instructor_id }.uniq
    @instructors = Instructor.active.find(today_instructor_ids)
    @date = Date.today
  end

  def show
    redirect_to_profile
    @instructor = Instructor.find(params[:id])
    @schedules = @instructor.schedules.without_personal_reservation
    @dates = uniq_dates(@schedules)
  end

  def tomorrow
    tomorrow_instructor_ids = Schedule.tomorrow.map{|s| s.instructor_id }.uniq
    @instructors = Instructor.active.find(tomorrow_instructor_ids)
    @date = Date.tomorrow
    render "index"
  end

  private
  def redirect_to_profile
    if current_instructor && !current_instructor.name
      redirect_to edit_instructor_registration_path
    end
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_instructor.html.erb
<div class="user-info">
  <%= link_to instructor_path(instructor) do %>
    <% if instructor.icon.attached? %>
      <%= image_tag instructor.icon %>
    <% else %>
      <%= image_tag "camera.png" %>
    <% end %>
    <div class="name-status">
      <%= instructor.name %>
      <% case instructor.status %>
        <% when "内定者" %>
          <span class="green-back"><%= instructor.status %></span>
        <% when "社会人" %>
          <span class="red-back"><%= instructor.status %></span>
      <% end %>
      <p>
        <%=
          "年齢: #{instructor.age}
          #{instructor.industry}/#{instructor.occupation}
          #{instructor.company if instructor.is_public}"
          %>
      </p>
    </div>
    <div class="profile">
      <div>ひとこと</div>
      <%= simple_format(instructor.profile) %>
    </div>
    <div class="start-times">
      <% instructor.schedules.each do |s| %>
        <% if s.date == @date %>
          <% if s.reservations.find{|r| r.course == "group" } && s.available?("group") %>
            <span class="group-time">
              <%= s.start_time.strftime("%-H:%M") %>
            </span>
          <% elsif s.reservations.empty? %>
            <span>
              <%= s.start_time.strftime("%-H:%M") %>
            </span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/instructors/index.html.erb
<%= render "application/header" %>
<div class="back-gray">
  <div class="search-field">
    <% if request.path == "/instructors" %>
      <button class="today">
        今日
      </button>
      <%= link_to tomorrow_instructors_path do %>
        <button class="tomorrow">
          明日
        </button>
      <% end %>
    <% else %>
      <%= link_to instructors_path do %>
        <button class="today">
          今日
        </button>
      <% end %>
      <button class="tomorrow">
        明日
      </button>
    <% end %>
  </div>
  <h2 class="search-title">講師を探す</h2>

  <% @instructors.each do |i| %>
    <%= render i %>
  <% end %>

  <% if @instructors.empty? %>
    <h3>条件に該当する講師はいません<h3>
  <% end %>
</div>

app/views/instructors/show.html.erb
<%= render "application/header" %>

<div class="back-gray">

  <%= render @instructor %>

  <% if current_student %>
    <h4>予約可能日時</h4>
    <p class="align-center">予約は面談開始時刻の3時間前まで可能です</p>
    <%= render "schedules/schedules", schedules: @schedules, dates: @dates, type: "public" %>

    <div class="box-wrapper">
      <div>
        <div class="red-box"></div>
        <span>グループ面談</span>
      </div>
    </div>
  <% end %>

  <% if @instructor.id == current_instructor&.id %>
    <div class="link-wrapper">
      <%= link_to "マイページを編集", edit_instructor_registration_path  %>
    </div>
  <% end %>
</div>