config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :students, controllers: {
        registrations: 'students/registrations',
        sessions: 'students/sessions'
      }

  devise_for :instructors, controllers: {
        registrations: 'instructors/registrations',
        sessions: 'instructors/sessions'
      }

  resources :instructors do
    collection do
      get :tomorrow
    end
  end

  resources :students

  resources :schedules, only: [:new, :create, :destroy, :index, :show] do
    collection do
      get :courses
    end
    resources :reservations do
      collection do
        get :personal
        get :group
      end
    end
    resources :meetings, only: [:new, :create]
  end

  resources :reservations

  resources :meetings do
    resources :reviews, only: [:new, :create, :index]
    resources :messages
  end

  resources :contacts, only: [:new, :create, :index]


  root "users#sign_up"
  get "/users/sign_in"
  get "/users/sign_up"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:sign_in, :sign_up]
  before_action :redirect_to_top, only: [:sign_in, :sign_up]

  def sign_in
  end

  def sign_up
  end

  private
  def redirect_to_top
    if current_student || current_instructor
      redirect_to instructors_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/sign_in.html.erb
<div class="back-grad">
  <h3>ログイン</h3>
  <%= link_to new_student_session_path do %>
    就活生の方
  <% end %>
  <%= link_to new_instructor_session_path do %>
    内定者・社会人の方
  <% end %>
  <div class="bottom-link-wrapper">
    <%= link_to "無料会員登録はこちら", "/users/sign_up", class: "bottom-link" %>
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="back-grad">
  <h3>会員登録</h3>
  <%= link_to new_student_registration_path do %>
    就活生の方
  <% end %>
  <%= link_to new_instructor_registration_path do %>
    内定者・社会人の方
  <% end %>
  <div class="bottom-link-wrapper">
    <%= link_to "登録済みの方はこちら", "/users/sign_in", class: "bottom-link" %>
  </div>
</div>