config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :students, controllers: {
        registrations: 'students/registrations',
        sessions: 'students/sessions'
      }

  devise_for :instructors, controllers: {
        registrations: 'instructors/registrations',
        sessions: 'instructors/sessions'
      }

  resources :instructors do
    collection do
      get :tomorrow
    end
  end

  resources :students

  resources :schedules, only: [:new, :create, :destroy, :index, :show] do
    collection do
      get :courses
    end
    resources :reservations do
      collection do
        get :personal
        get :group
      end
    end
    resources :meetings, only: [:new, :create]
  end

  resources :reservations

  resources :meetings do
    resources :reviews, only: [:new, :create, :index]
    resources :messages
  end

  resources :contacts, only: [:new, :create, :index]


  root "users#sign_up"
  get "/users/sign_in"
  get "/users/sign_up"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :instructor
  has_many :reservations, dependent: :destroy
  has_one :meeting, dependent: :destroy

  validates :date, presence: true
  validates :start_time, presence: true, uniqueness: { scope: [:date, :instructor_id], message: "が既存のシフトと重複しています" }
  validate :is_before_deadline

  default_scope {order(:date, :start_time)}

  scope :after_today, -> {where("date >= ?", Date.today)}
  scope :today, -> {where(date: Date.today)}
  scope :tomorrow, -> {where(date: Date.tomorrow)}

  def self.without_personal_reservation
    after_today.reject{|s| s.reservations&.first&.course == "personal" }
  end

  def available?(course)
    case course
      when "personal"
        max = 1
      when "group"
        max = 5
    end
    self.reservations.count < max
  end

  def compare_start_time(dif)
    self.start_time.strftime("%-H%M").to_i < Time.current.strftime("%-H%M").to_i + dif
  end

  def previous?
    self.date < Date.today || self.date == Date.today && self.compare_start_time(0)
  end

  private
  def is_before_deadline
    if date < Date.today || date == Date.today && compare_start_time(300)
      errors.add(:base, "日時は今から3時間後以降を選択してください")
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_instructor!, except: [:show, :courses]
  before_action :authenticate_student!, only: [:show, :courses]
  before_action :redirect_if_not_reviewed, only: [:create]
  before_action :redirect_to_profile_edit, only: [:create]

  def index
    @schedules = current_instructor.schedules.after_today
    @dates = uniq_dates(@schedules)
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def new
    @schedule = current_instructor.schedules.build
  end

  def create
    @schedule = current_instructor.schedules.build(schedule_params)
    if @schedule.save
      redirect_to schedules_path
    else
      render "new"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedules_path
  end


  private
  def schedule_params
    params.require(:schedule).permit(:date, :start_time)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_schedules.html.erb
<% dates.each do |d| %>
  <div class="day-schedule">
    <%= d.strftime("%-m/%-d") %>
    <div class="start-times">
      <% schedules.each do |s| %>
        <% if s.date == d %>
            <% if type == "private" %>
              <% if !s.reservations.empty? && !s.meeting %>
                <span class="reserved-time"><%= link_to s.start_time.strftime("%H:%M"), new_schedule_meeting_path(s) %></span>
              <% elsif s.reservations.find{|r| r.course == "personal" } %>
                <span class="personal-time"><%= s.start_time.strftime("%H:%M") %></span>
              <% elsif s.reservations.find{|r| r.course == "group" } %>
                <span class="group-time"><%= s.start_time.strftime("%H:%M") %></span>
              <% else %>
                <%=
                  link_to s.start_time.strftime("%H:%M"), schedule_path(s.id),
                  {method: :delete, data: {confirm: "このシフトを削除しますか？"}}
                  %>
              <% end %>
            <% else %>
              <% if s.reservations.find{|r| r.course == "group" } %>
                <span class="group-time">
                  <%= link_to_if current_student, s.start_time.strftime("%H:%M"), group_schedule_reservations_path(s) %>
                </span>
              <% elsif s.reservations.size == 0 %>
                <% if current_student %>
                  <%= link_to s.start_time.strftime("%H:%M"), schedule_path(s) %>
                <% else %>
                  <span><%= s.start_time.strftime("%H:%M") %></span>
                <% end %>
              <% end %>
            <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

<% if dates.empty? %>
  <p class="no-schedule">シフトが登録されていません</p>
<% end %>

app/views/schedules/courses.html.erb
<%= render "application/header" %>
<div class="back-gray">

  <h3>コース詳細</h3>

  <div class="personal-course">
    <h3 class="course-name">個人面談</h3>
    <p>1回30分、社会人や内定者の方と1対1で面接練習ができます。
      企業研究をしたり自己分析をしたりと使い方は様々！</p>
    <p>内定を掴み取る1歩にしてください。</p>
  </div>

  <div class="group-course">
    <h3 class="course-name">グループ面談</h3>
    <p>1回30分、他の就活生の方とグループディスカッションの練習ができます。
      社会人の方にみてもらいながらグループディスカッションの練習をする機会はなかなかありません。</p>
    <p>有効に使いましょう！</p>
  </div>

</div>

app/views/schedules/index.html.erb
<%= render "application/header" %>

<div class="back-gray">
  <h2 class="search-title">シフト確認</h2>

  <%= render "schedules", schedules: @schedules, dates: @dates, type: "private" %>

  <div class="box-wrapper">
    <div>
      <div class="green-box"></div>
      <span>個人面談</span>
    </div>

    <div>
      <div class="red-box"></div>
      <span>グループ面談</span>
    </div>

    <div>
      <div class="blue-box"></div>
      <span>フォーム未回答</span>
    </div>
  </div>

  <div class="link-wrapper">
    <%= link_to "新しくシフトを登録", new_schedule_path %>
  </div>
</div>

app/views/schedules/new.html.erb
<%= render "application/header" %>
<div class="back-gray">
  <h2 class="search-title">シフト登録</h2>

  <%= form_for(@schedule) do |f| %>
    <% if @schedule.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @schedule.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :date %>
    <%= f.date_select :date, {use_month_numbers: true} %>

    <%= f.label :start_time %>
    <%= f.time_select :start_time, {minute_step: 30, start_hour: 9} %>
  　<%= "から 30分間" %>

    <div class="form-actions">
      <%= f.submit "登録する" %>
    </div>

  <% end %>
  <div class="link-wrapper">
    <%= link_to "登録したシフトの確認", schedules_path %>
  </div>
</div>

app/views/schedules/show.html.erb
<%= render "application/header" %>
<div class="back-gray">

  <%= render @schedule.instructor %>

  <h3>コースを選択</h3>

  <div class="courses-wrapper">
    <button class="personal">
      <%= link_to "個人面談", personal_schedule_reservations_path(@schedule) %>
    </button>
    <button class="group">
      <%= link_to "グループ面談", group_schedule_reservations_path(@schedule) %>
    </button>
  </div>

  <div class="bottom-link-wrapper">
    <%= link_to "コースについて詳しくみる", courses_schedules_path, class: "bottom-link" %>
  </div>

</div>