config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :students, controllers: {
        registrations: 'students/registrations',
        sessions: 'students/sessions'
      }

  devise_for :instructors, controllers: {
        registrations: 'instructors/registrations',
        sessions: 'instructors/sessions'
      }

  resources :instructors do
    collection do
      get :tomorrow
    end
  end

  resources :students

  resources :schedules, only: [:new, :create, :destroy, :index, :show] do
    collection do
      get :courses
    end
    resources :reservations do
      collection do
        get :personal
        get :group
      end
    end
    resources :meetings, only: [:new, :create]
  end

  resources :reservations

  resources :meetings do
    resources :reviews, only: [:new, :create, :index]
    resources :messages
  end

  resources :contacts, only: [:new, :create, :index]


  root "users#sign_up"
  get "/users/sign_in"
  get "/users/sign_up"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    if resource.class == Student
      instructors_path
    elsif resource.class == Instructor
      schedules_path
    end
  end

  def redirect_to_top(notice)
    if current_student
      redirect_to instructors_path, notice: notice
    elsif current_instructor
      redirect_to schedules_path, notice: notice
    end
  end

  def authenticate_user!
    if !student_signed_in? && !instructor_signed_in?
      authenticate_student!
      authenticate_instructor!
    end
  end

  def redirect_to_profile_edit
    if current_student && current_student.name == nil
      redirect_to edit_student_registration_path, alert: "プロフィール登録をしてください"
    elsif current_instructor && current_instructor.name == nil
      redirect_to edit_instructor_registration_path, alert: "プロフィール登録をしてください"
    end
  end

  def redirect_if_not_reviewed
    if current_student && current_student.not_reviewed?
      redirect_to meetings_path, alert: "過去のレビューが残っています"
    elsif current_instructor && current_instructor.not_reviewed?
      redirect_to meetings_path, alert: "過去のレビューが残っています"
    end
  end

  def uniq_dates(schedules)
    return schedules.map{|s| s.date }.uniq.sort
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def meetings_count
    if current_student
      current_student&.meetings&.select{|m| !m&.reviewed(current_student)}.size
    else
      current_instructor&.meetings&.select{|m| !m&.reviewed(current_instructor)}.size
    end
  end
end

app/views/application/_header.html.erb
<header>
  <h3>Bolstering Career</h3>
  <div class="menu-wrapper">
    <%= image_tag "menu.png", id: "menu-link" %>
    <% if meetings_count != 0 %>
      <span class="notification">●</span>
    <% end %>
  </div>
</header>
<% if !current_student&.name && !current_instructor&.name %>
  <div class="profile-alert">
    <%= link_to_if current_student, "プロフィールを登録してください", edit_student_registration_path do %>
    <% end %>
    <%= link_to_if current_instructor, "プロフィールを登録してください", edit_instructor_registration_path do %>
    <% end %>
  </div>
<% end %>
<div id="close-menu">
</div>
<div id="menu">
  <div class="menu-content">
    <% if current_student %>
      <%= link_to "講師を探す", instructors_path %>
      <%= link_to "予約中の面談", reservations_path %>
      <%= link_to meetings_path do %>
        面談情報
        <% if meetings_count != 0 %>
          <span><%= meetings_count %></span>
        <% end %>
      <% end %>
      <%= link_to "マイページ", student_path(current_student) %>
      <%= link_to "お問い合わせ", new_contact_path %>
      <%= link_to "ログアウト", destroy_student_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} %>
    <% end %>
    <% if current_instructor %>
      <%= link_to "シフト登録", new_schedule_path %>
      <%= link_to "シフト確認", schedules_path %>
      <%= link_to meetings_path do %>
        面談情報
        <% if meetings_count != 0 %>
          <span><%= meetings_count %></span>
        <% end %>
      <% end %>
      <%= link_to "マイページ", instructor_path(current_instructor) %>
      <%= link_to "お問い合わせ", new_contact_path %>
      <%= link_to "ログアウト", destroy_instructor_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} %>
    <% end %>
  </div>
</div>